const fs = require("fs");
let content = fs.readFileSync("src/components/marinovate/MarinovateHome.tsx", "utf8");
content = content.replace(/text-\[var\(--ink\)\]\/(\d+)/g, "text-ink/$1");
content = content.replace(/bg-\[var\(--forest-deep\)\]\/(\d+)/g, "bg-forest-deep/$1");
content = content.replace(/text-\[var\(--forest-deep\)\]\/(\d+)/g, "text-forest-deep/$1");
content = content.replace(/from-\[var\(--forest-deep\)\]\/(\d+)/g, "from-forest-deep/$1");
content = content.replace(/via-\[var\(--forest-deep\)\]\/(\d+)/g, "via-forest-deep/$1");
content = content.replace(/shadow-\[var\(--forest-deep\)\]\/(\d+)/g, "shadow-forest-deep/$1");
content = content.replace(/border-\[var\(--forest-deep\)\]\/(\d+)/g, "border-forest-deep/$1");
fs.writeFileSync("src/components/marinovate/MarinovateHome.tsx", content);
